server:
  port: 8888
spring:
  application:
    name: ms-admin-server-config
#Configuracion Local
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          searchLocations: file:///D:/Galaxy/Proyecto-Github/Nutrition-app/Microservices-project/ms-admin-server-data