server:
  port: 8890
spring:
  application:
    name: ms-admin-server-admin

#Eureka
#Registry Client
eureka:
  client:
    registryFetchIntervalSeconds: 5
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8889/eureka
