server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ms_user_customer_management
    username: root
    password: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  # Spring Boot Admin
  boot:
    admin:
      client:
        url: http://localhost:8890

# Registry Client
eureka:
  client:
    registryFetchIntervalSeconds: 5
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8889/eureka

# Actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"