spring:
  application:
    name: ms-vaccines-dose-management

#  cloud:
#    config:
#      uri: http://localhost:8888
#      fail-fast: true
#      retry:
#        max-attempts: 20
#        max-interval: 15000
#        initial-interval: 10000
#server:
#  port: 8080
#
#spring:
#  jpa:
#    database: postgresql
#    show-sql: true
#    hibernate:
#      ddl-auto: update
#    properties:
#      hibernate:
#        format_sql: true
#  datasource:
#    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://localhost/ms_service_vaccines
#    username: postgres
#    password: mysql


#server:port=8080
#spring.jpa.database=postgresql
#spring.jpa.show-sql=true
#spring.jpa.hibernate.ddl-auto=update
#
#spring.jpa.properties.hibernate.format_sql=true
#spring.datasource.driver-class-name=org.postgresql.Driver
#spring.datasource.url=jdbc:postgresql://localhost/ms_service_vaccines
#spring.datasource.username=postgres
#spring.datasource.password=mysql
